import Head from "next/head";

import CV from "../components/CV";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,200;8..144,300;8..144,400;8..144,500;8..144,600&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="flex bg-[#EEEEEE]">
        <section className="bg-[#E7E7E7] shadow-2xl w-[400px] h-screen"></section>
        <div className="m-auto">
          {/* <h1 className="text-[#444444] mx-auto text-center text-xl">Hello</h1> */}
          <section className="bg-white rounded-md scale-100 transition-all hover:scale-110 hover:shadow-xl shadow-sm p-8 resize w-[595px] h-[842px]">
            <CV className="" />
          </section>
        </div>
      </main>
    </>
  );
}
